### PR TITLE
Xchourio/datasets

### PR DESCRIPTION
**Pull request by xchourio**
OISST2p1.SST, NNRP.UA, NNRP.VA added

### CODE REVIEW

**Review by awrobertson — APPROVED** [review]
Thank you!

**Review by aaron-kaplan — APPROVED** [review]
Looks fine to the eye. I haven't tested it. The release process is onerous, so make sure you've tested everything before we publish it. The way I test is to

- create a conda environment called pycpt-dev from the latest lock file https://github.com/iri-pycpt/notebooks/releases/tag/v2.8.1
- cd pycpt/cpt-dl
- pip install -e . # overwrites the packaged version with the version that's in your source code
- then run a notebook that exercises the new functionality.

The cptdl version number occurs in three places: setup.py, conda-recipe/meta.yaml, and __init__.py in the source package dir. Please increment the version number in all three. Also change the author from Kyle to just "IRI" while you're in there.

I will write up instructions for publishing the new package separately.

**Comment by awrobertson** [comment]
Thanks Aaron

**Comment by xchourio** [comment]
Done! I tested it (OISST2p1.SST needed a renameGRID from lon and lat to X / Y). After that, all new Obs dataset works well, and I also incremented the version number.

**Pull request merged**
